package abdaty_technologie.API_Invest.Entity.Enum;

// Nationalité (conseil: préférer un code ISO String en DB.
// Ici quelques valeurs de base + OTHER)
public enum Nationalites {
    AFGHANE("Afghane"),
    ALBANAISE("Albanaise"),
    ALGÉRIENNE("Algérienne"),
    ALLEMANDE("Allemande"),
    AMÉRICAINE("Americaine"),
    ANDORRANE("Andorran"),
    ANGOLAISE("Angolaise"),
    ANTIGUAISE("Antiguaise"),
    ARGENTINE("Argentine"),
    ARMÉNIENNE("Arménienne"),
    AUSTRALIENNE("Australienne"),
    AUTRICHIENNE("Autrichienne"),
    AZERBAÏDJANAISE("Azerbaïdjanaise"),
    BAHAMÉENNE("Bahaméenne"),
    BAHREÏNIENNE("Bahreïenne"),
    BANGLADAISE("Bangladeshienne"),
    BARBADIENNE("Barbadienne"),
    BELGE("Belge"),
    BÉLIZIENNE("Belizienne"),
    BÉNINOISE("Beninoise"),
    BHOUTANAISE("Bhoutanaise"),
    BIÉLORUSSE("Beloroussienne"),
    BIRMANE("Birmane"),
    BOLIVIENNE("Bolivienne"),
    BOSNIAQUE("Bosniaque"),
    BOTSWANAISE("Botswanaise"),
    BRÉSILIENNE("Bresilienne"),
    BRITANNIQUE("Britannique"),
    BRUNÉIENNE("Brunéienne"),
    BULGARE("Bulgar"),
    BURKINABÈ("Burkinabè"),
    BURUNDAISE("Burundaise"),
    CAMBODGIENNE("Cambodgienne"),
    CAMEROUNAISE("Camerounaise"),   
    CANADIENNE("Canadienne"),
    CAP_VERDIENNE("Cap-Verdienne"),
    CENTRAFRICAINE("Centrafricaine"), 
    CHILIENNE("Chilienne"),
    CHINOISE("Chinoise"),
    CHYPRIOTE("Chypriote"),
    COLOMBIENNE("Colombienne"),
    COMORIENNE("Comorienne"),
    CONGOLAISE_RDC("Congolaise RDC"),
    CONGOLAISE_CONGO_BRAZZAVILLE("Congolaise Congo Brazzaville"),
    COSTARICIENNE("Costaricienne"),
    CROATE("Croate"),
    CUBAINE("Cubaine"),
    DANOISE("Danaise"),
    DJIBOUTIENNE("Djiboutienne"),
    DOMINICAINE("Dominicaine"),
    DOMINIQUAISE("Dominiquaise"),
    ÉGYPTIENNE("Egyptienne"),
    ÉMIRIENNE("Emirienne"),
    ÉQUATORIENNE("Equatorienne"),   
    ÉRYTHRÉENNE("Erythreenne"),
    ESPAGNOLE("Espagnole"),
    ESTONIENNE("Estonienne"),
    ESWATINIENNE("Eswatinienne"),
    ÉTHIOPIENNE("Ethiopienne"),
    FIDJIENNE("Fidjienne"),
    FINLANDAISE("Finlandaise"),
    FRANÇAISE("Française"),
    GABONAISE("Gabonaise"),
    GAMBIENNE("Gambienne"),
    GÉORGIENNE("Georgienne"),
    GHANÉENNE("Ghanéenne"),
    GRECQUE("Grecque"),
    GRENADIENNE("Grenadienne"),
    GUATÉMALTÈQUE("Guatemalteque"),
    GUINÉENNE("Guineenne"),
    BISSAU_GUINÉENNE("Bissau Guineenne"),
    GUYANIENNE("Guyanienne"),
    HAÏTIENNE("Haïtienne"),
    HONDURIENNE("Hondurienne"),
    HONGROISE("Hongroise"),
    INDIENNE("Indienne"),
    INDONÉSIENNE("Indonésienne"),
    IRAKIENNE("Irakienne"),
    IRANIENNE("Iranienne"),
    IRLANDAISE("Irlandaise"),
    ISLANDAISE("Islandaise"),
    ISRAÉLIENNE("Israélienne"),
    ITALIENNE("Italienne"),
    IVOIRIENNE("Ivoirienne"),
    JAMAÏCAINE("Jamaïcaine"),
    JAPONAISE("Japonaise"),
    JORDANIENNE("Jordanienne"),
    KAZAKHE("Kazakhe"),
    KÉNYANE("Kényane"),
    KIRGHIZE("Kirghize"),
    KIRIBATIENNE("Kiribatienne"),
    KOWEÏTIENNE("Koweïtienne"),
    LAOTIENNE("Laotienne"),
    LETTONE("Lettone"),
    LIBANAISE("Libanaise"),
    LIBÉRIENNE("Libérienne"),
    LIBYENNE("Libyenne"),
    LIECHTENSTEINOISE("Liechtensteinoise"),
    LITUANIENNE("Lituanienne"),
    LUXEMBOURGEOISE("Luxembourgeoise"),
    MACÉDONIENNE("Macédonienne"),
    MALAISIENNE("Malaisienne"),
    MALAWITE("Malawite"),
    MALDIVIENNE("Maldivienne"),
    MALIENNE("Malienne"),
    MALTAISE("Maltaise"),
    MAROCAINE("Marocaine"),
    MARSHALLAISE("Marshallaise"),
    MAURICIENNE("Mauricienne"),
    MAURITANIENNE("Mauritanienne"),
    MEXICAINE("Mexicaine"),
    MICRONÉSIENNE("Micronésienne"),
    MOLDAVE("Moldave"),
    MONÉGASQUE("Monégasque"),
    MONGOLE("Mongole"),
    MONTÉNÉGRINE("Monténégrove"),
    MOZAMBICAINE("Mozambicaine"),
    NAMIBIENNE("Namibienne"),
    NAURUANE("Nauruanne"),
    NÉERLANDAISE("Néerlandaise"),
    NÉO_ZÉLANDAISE("Néo-Zélandaise"),
    NÉPALAIS("Népalais"),
    NIGÉRIANE("Nigériane"),
    NIGÉRIENNE("Nigérienne"),
    NORD_CORÉENNE("Nord-Coréenne"),
    NORVÉGIENNE("Norvégienne"),
    OMANAISE("Omanaise"),
    PAKISTANAISE("Pakistanaise"),
    PALESTINIENNE("Palestinienne"),
    PANAMÉENNE("Panaméenne"),
    PAPOUASIENNE_NÉO_GUINÉENNE("Papouasienne Neo-Guinéenne"),
    PARAGUAYENNE("Paraguayenne"),
    PÉRUVIENNE("Peruvienne"),
    PHILIPPINE("Philippine"),
    POLONAISE("Polonaise"),
    PORTUGAISE("Portugaise"),
    QATARIE("Qatarie"),
    ROUMAINE("Roumaine"),
    RUSSE("Russe"),
    RWANDAISE("Rwandaise"),
    SAINT_LUCIENNE("Saint Lucienne"),
    SAINT_MARINAISE("Saint Marinaise"),
    SAINT_VINCENTAISÉ_ET_GRENADINE("Saint Vincentaisé et Grenadine"),
    SALOMONIENNE("Salomonienne"),
    SALVADORIENNE("Salvadorienne"),
    SAMOANE("Samoaenne"),
    SAO_TOMÉENNE("São Toméenne"),
    SAOUDIENE("Saoudienne"),
    SÉNÉGALAISE("Sénégalaise"),
    SERBE("Serbe"),
    SEYCHELLOISE("Seychelloise"),
    SIERRA_LEONAISE("Sierra Leoneaise"),
    SINGAPOURIENNE("Singapourienne"),
    SLOVAQUE("Slovaque"),
    SLOVÈNE("Slovène"),
    SOMALIENNE("Somalienne"),
    SOUDANAISE("Soudanaise"),
    SUD_CORÉENNE("Sud-Coréenne"),
    SUD_SOUDANAISE("Sud-Soudanaise"),
    SRI_LANKAISE("Sri Lankaise"),
    SUÉDOISE("Suédoise"),
    SUISSE("Suisse"),
    SYRIENNE("Syrienne"),
    TADJIKE("Tadjike"),
    TANZANIENNE("Tanzanienne"),
    TCHADIENNE("Tchadienne"),
    TCHÈQUE("Tchèque"),
    THAÏLANDAISE("Thaïlandaise"),
    TIMORAISE("Timoraise"),
    TOGOLAISE("Togolaise"),
    TONGIENNE("Tongienne"),
    TRINITÉENNE_ET_TOBAGAISE("Trinitéenne et Tobagaise"),
    TUNISIENNE("Tunisienne"),
    TURKMÈNE("Turkmène"),
    TURQUE("Turque"),
    TUVALUANE("Tuvaluane"),
    UKRAINIENNE("Ukrainienne"),
    URUGUAYENNE("Uruguayenne"),
    OUZBÈKE("Ouzbèque"),
    VANUATAISE("Vanuataise"),
    CITOYENNE_DU_SAINT_SIÈGE_VATICAN("Citoyenne du Saint-Siège Vatican"),
    VÉNÉZUÉLIENNE("Vénézuélienne"),
    VIETNAMIENNE("Vietnamienne"),
    YÉMÉNITE("Yéménite"),
    ZAMBIENNE("Zambienne"),
    ZIMBABWEENNE("Zimbabweenne");
    
    private final String value;

    Nationalites(String value) {
        this.value = value;
    }
    public String getValue() {
        return value;
    }
}
